## 03. Modélisation 

L’objectif de cette section est d’évaluer l’impact du rééquilibrage par **SMOTE** (appliqué uniquement sur le jeu d’entraînement) sur les performances de modèles de classification. Nous analyserons la capacité du modèle à détecter la classe minoritaire avant et après rééquilibrage. 

Nous comparons deux modèles : **régression logistique** et **Random Forest**, appliquée sans rééquilibrage de la base de données et avec réequilibrage.

Dans un contexte de classes déséquilibrées, nous analysons le ROC-AUC et la matrice de confusion de chaque modèle afin d’étudier le compromis entre :
- FN : résiliations non détectées (coût potentiellement élevé),
- FP : fausses alertes (coût commercial / opérationnel).

/!\ Certaines parties de ce notebook prennent plusieurs minutes à être exécutées.

### 1- Importation des données et packages 

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np
import joblib

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report, roc_auc_score, confusion_matrix
)
from sklearn.model_selection import RandomizedSearchCV

import statsmodels.api as sm
from imblearn.over_sampling import SMOTE

In [ ]:
# Important : la séparation train/test a été faite en amont (notebook 2).
IN_DIR = Path("..") / "data" / "processed"

data = np.load(IN_DIR / "eudirectlapse_num_scaled_split.npz", allow_pickle=True)

X_train_num_scaled = data["X_train"]
X_test_num_scaled = data["X_test"]
y_train = data["y_train"]
y_test = data["y_test"]
num_cols = data["num_cols"].tolist()

scaler = joblib.load(IN_DIR / "scaler_num.joblib")

print(X_train_num_scaled.shape, X_test_num_scaled.shape)

(17295, 12) (5765, 12)


In [75]:
print("Train target rate:", y_train.mean())
print("Test target rate:", y_test.mean())

Train target rate: 0.1281295172015033
Test target rate: 0.1280138768430182


### 2- Régression logistique 
La régression logistique est un modèle linéaire simple et interprétable.  
Dans un contexte de déséquilibre, elle peut privilégier la classe majoritaire, ce qui se traduit par un faible nombre de résiliations détectées.

#### a - Modèle de référence : Régression logistique (sans SMOTE)

Une régression logistique est estimée à l’aide de statsmodels afin d’obtenir :
- les coefficients du modèle,
- les erreurs standards,
- les p-values associées à chaque variable explicative.

Cette approche permet d’analyser l’impact individuel de chaque variable sur la probabilité de résiliation et d’identifier les variables statistiquement non significatives.


In [ ]:
X_train_df = pd.DataFrame(X_train_num_scaled, columns=num_cols)
X_test_df  = pd.DataFrame(X_test_num_scaled,  columns=num_cols)
X_train_sm = sm.add_constant(X_train_df, has_constant="add")

logit_full = sm.Logit(y_train, X_train_sm)
res_full = logit_full.fit(disp=False, method="lbfgs", maxiter=200)

print(res_full.summary())

                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                17295
Model:                          Logit   Df Residuals:                    17283
Method:                           MLE   Df Model:                           11
Date:                Sat, 03 Jan 2026   Pseudo R-squ.:                 0.01676
Time:                        15:00:45   Log-Likelihood:                -6509.8
converged:                       True   LL-Null:                       -6620.8
Covariance Type:            nonrobust   LLR p-value:                 2.041e-41
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                 -1.9619      0.024    -82.868      0.000      -2.008      -1.916
polholder_age         -0.1403      0.028     -4.978      0.000      -0.196      -0.085
policy_age          

Plusieurs variables liées aux montants de prime présentent des p-values égales à 1 (prem_final, prem_last,prem_charge_rel). De plus, la variable policy_nbcontract a un p-value de 0,66 donc la variable n'a aucun effet significatif. Les variables prem_market et prem_vs_market ne sont pas significatives.

Seules les variables de variation relative de prime ont été conservées.

In [96]:
vars_to_drop = [
    "prem_last",
    "prem_final",
    "prem_change_abs",
    "prem_vs_market",
    "prem_market",
    "policy_nbcontract"
]

X_train_reduced = X_train_df.drop(columns=vars_to_drop)
X_test_reduced  = X_test_df.drop(columns=vars_to_drop)

X_train_sm = sm.add_constant(X_train_reduced, has_constant="add")

res_clean = sm.Logit(y_train, X_train_sm).fit(disp=False, method="lbfgs", maxiter=200)
print(res_clean.summary())

                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                17295
Model:                          Logit   Df Residuals:                    17288
Method:                           MLE   Df Model:                            6
Date:                Sat, 03 Jan 2026   Pseudo R-squ.:                 0.01263
Time:                        15:24:29   Log-Likelihood:                -6537.2
converged:                       True   LL-Null:                       -6620.8
Covariance Type:            nonrobust   LLR p-value:                 1.701e-33
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                 -1.9515      0.023    -83.174      0.000      -1.997      -1.906
polholder_age         -0.1565      0.028     -5.586      0.000      -0.211      -0.102
policy_age          

Une fois la sélection des variables effectuées nous pouvons entrainer le modèle avec sklearn.

In [97]:
model1 = LogisticRegression(max_iter=1000)
model1.fit(X_train_reduced, y_train)

LogisticRegression(max_iter=1000)

Le paramètre max_iter est fixé à 1000 afin de garantir la convergence de l’algorithme d’optimisation, en particulier dans un contexte de données déséquilibrées et standardisées.

In [98]:
y_pred_base = model1.predict(X_test_reduced)
y_proba_base = model1.predict_proba(X_test_reduced)[:, 1]

In [106]:
roc_auc = roc_auc_score(y_test, y_proba_base)

# Tableau récapitulatif
metrics_summary = pd.DataFrame({
    "Metric": ["ROC-AUC"],
    "Value": [roc_auc]
})

print("=== Performance summary ===")
display(metrics_summary)

print("=== Confusion matrix ===")
display(pd.DataFrame(
    confusion_matrix(y_test, y_pred_base),
    index=["True 0", "True 1"],
    columns=["Pred 0", "Pred 1"]
))

=== Performance summary ===


Metric     Value
0  ROC-AUC  0.571412

=== Confusion matrix ===


Pred 0  Pred 1
True 0    5027       0
True 1     738       0

Avec le seuil de décision par défaut (0.5), le modèle ne prédit aucune résiliation. Ce comportement s’explique par le fort déséquilibre de la variable cible. Bien que l’AUC indique une capacité de discrimination supérieure au hasard (0,57 > 0,5), le modèle ne peut pas être utilisé pour étudier les résiliations. Plusieurs approches peuvent alors être envisagées pour améliorer la détection de la classe minoritaire :

– un ajustement du seuil de décision 

– un rééquilibrage des classes avec la méthode SMOTE.

#### b - Régression logistique avec rééquilibrage (SMOTE)

Dans cette section, nous évaluons l’impact du rééquilibrage des classes par la méthode SMOTE sur les performances d’une régression logistique.  
SMOTE est appliqué uniquement sur le jeu d’entraînement (après sélection des variables) afin d’éviter toute fuite d’information vers le jeu de test.


In [101]:
smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train_reduced ,
    y_train
)

print("Distribution après SMOTE :")
print(pd.Series(y_train_smote).value_counts(normalize=True))

Distribution après SMOTE :
0    0.5
1    0.5
Name: proportion, dtype: float64


Après application de SMOTE, la distribution de la variable *lapse* dans le jeu
d’entraînement est équilibrée. Les observations synthétiques sont générées
uniquement à partir des données d’apprentissage. On peut à nouveau effectuer une régression logistique sur cette nouvelles base des données. 


In [102]:
model_smote = LogisticRegression(max_iter=1000)
model_smote.fit(X_train_smote, y_train_smote)

LogisticRegression(max_iter=1000)

In [104]:
y_pred_smote = model_smote.predict(X_test_reduced)
y_proba_smote = model_smote.predict_proba(X_test_reduced)[:, 1]

In [ ]:
roc_auc = roc_auc_score(y_test, y_proba_smote)

metrics_smote = pd.DataFrame({
    "Metric": ["ROC-AUC"],
    "Value": [roc_auc]
})

print("=== Logistic Regression + SMOTE — Performance summary ===")
display(metrics_smote)

print("=== Confusion matrix ===")
display(pd.DataFrame(
    confusion_matrix(y_test, y_pred_smote),
    index=["True 0", "True 1"],
    columns=["Pred 0", "Pred 1"]
))

print("=== Classification report ===")
print(classification_report(y_test, y_pred_smote, digits=4))

=== Logistic Regression + SMOTE — Performance summary ===


Metric     Value
0  ROC-AUC  0.570574

=== Confusion matrix ===


Pred 0  Pred 1
True 0    2619    2408
True 1     311     427

=== Classification report ===
              precision    recall  f1-score   support

           0     0.8939    0.5210    0.6583      5027
           1     0.1506    0.5786    0.2390       738

    accuracy                         0.5284      5765
   macro avg     0.5222    0.5498    0.4487      5765
weighted avg     0.7987    0.5284    0.6046      5765



L’application de SMOTE modifie le comportement de la régression logistique. Le ROC-AUC reste du même ordre de grandeur que pour le modèle sans SMOTE. L’analyse des métriques usuels sur la classe minoritaire met en évidence une amélioration de la détection des résiliations.

La matrice de confusion montre que le modèle après rééquilibrage identifie correctement 427 résiliations (TP), contre aucune pour le modèle sans SMOTE. Le rappel de la classe minoritaire atteint ainsi 57,8 %, alors le modèle détecte correctement 57,8 % des résiliations. On remarque aussi que cette amélioration s’accompagne d’une augmentation du nombre de faux positifs (2 408).

Ces résultats confirment que SMOTE permet de rendre le modèle sensible à la classe d’intérêt, au prix d’un compromis entre détection des résiliations et augmentation des fausses alertes.

### 3 - Random Forest 
Dans cette section, nous évaluons les performances d’un modèle de Random Forest, d’abord sans rééquilibrage des classes, puis avec application de SMOTE sur le jeu d’entraînement.

La Random Forest est un modèle non-linéaire basé sur des arbres de décison. Elle est souvent plus flexible, mais peut également être affectée par le déséquilibre des classes.  

Contrairement à la régression logistique, la Random Forest ne repose pas sur des hypothèses de linéarité ou d’indépendance entre les variables. L’ensemble des variables explicatives est donc conservé.

#### a- Modèle de référence : Random Forest sans SMOTE



Un modèle de Random Forest de référence est tout d’abord entraîné à l’aide d’hyperparamètres standards afin d’établir un point de comparaison. Cette étape permet d’évaluer l’apport réel de l’optimisation des hyperparamètres réalisée par la suite.

In [112]:
rf_base = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf_base.fit(X_train_num_scaled, y_train)


RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [ ]:
y_pred_rf_base = rf_base.predict(X_test_num_scaled)
y_proba_rf_base = rf_base.predict_proba(X_test_num_scaled)[:, 1]

In [ ]:
roc_auc_rf_base = roc_auc_score(y_test, y_proba_rf_base)
print(f"ROC-AUC Random Forest : {roc_auc_rf_base:.4f}")

cm_rf_base = confusion_matrix(y_test, y_pred_rf_base)

display(pd.DataFrame(
    cm_rf_base,
    index=["True 0", "True 1"],
    columns=["Pred 0", "Pred 1"]
))

ROC-AUC Random Forest (baseline) : 0.5494


Pred 0  Pred 1
True 0    5008      19
True 1     734       4

##### Optimisation des hyperparamètres

La performance d’une Random Forest dépend fortement de plusieurs hyperparamètres :  la profondeur des arbres et le nombre minimal d’observations par feuille. Une recherche des hyperparamètres est réalisée afin d’identifier une configuration optimale tout en limitant le coût de calcul.

L’optimisation est conduite à l’aide d’une validation croisée à cinq folds.

In [115]:
param_dist = {
    "n_estimators": [200, 300, 500],
    "max_depth": [None, 5, 10],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 5]
}

rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

rs = RandomizedSearchCV(
    rf,
    param_distributions=param_dist,
    n_iter=10,
    scoring="roc_auc",
    cv=5,
    verbose=1,
    random_state=42
)

rs.fit(X_train_num_scaled, y_train)

print("Meilleurs hyperparamètres :")
print(rs.best_params_)


Fitting 5 folds for each of 10 candidates, totalling 50 fits
Meilleurs hyperparamètres :
{'n_estimators': 300, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_depth': 5}


In [130]:
rf_best = rs.best_estimator_

y_proba_rf_best = rf_best.predict_proba(X_test_num_scaled)[:, 1]
y_pred_rf_best = rf_base.predict(X_test_num_scaled)

In [132]:
roc_auc = roc_auc_score(y_test, y_proba_rf_best)

metrics_rf_base = pd.DataFrame({
    "Metric": ["ROC-AUC"],
    "Value": [roc_auc]
})

print("=== Random Forest — Performance summary ===")
display(metrics_rf_base)

print("=== Confusion matrix ===")
display(pd.DataFrame(
    confusion_matrix(y_test, y_pred_rf_best),
    index=["True 0", "True 1"],
    columns=["Pred 0", "Pred 1"]
))

print("=== Classification report ===")
print(classification_report(y_test, y_pred_rf_best, digits=4))


=== Random Forest — Performance summary ===


Metric     Value
0  ROC-AUC  0.587906

=== Confusion matrix ===


Pred 0  Pred 1
True 0    5008      19
True 1     734       4

=== Classification report ===
              precision    recall  f1-score   support

           0     0.8722    0.9962    0.9301      5027
           1     0.1739    0.0054    0.0105       738

    accuracy                         0.8694      5765
   macro avg     0.5230    0.5008    0.4703      5765
weighted avg     0.7828    0.8694    0.8124      5765



Comme la régression logistique, l’algorithme de random forest entraîné sans rééquilibrage a tendance à privilégier la classe majoritaire et peine à détecter les résiliations même après optimisation des paramètres.

#### b- Random Forest avec SMOTE

On applique SMOTE aux données d’entraînement (variables numériques standardisées), puis on entraîne la Random Forest sur ce jeu de données rééquilibré. 

In [124]:
smote = SMOTE(random_state=42)
X_train_rf_smote, y_train_rf_smote = smote.fit_resample(X_train_num_scaled, y_train)

rf_smote = RandomForestClassifier(
    n_estimators=300,
    max_depth=5,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

rf_smote.fit(X_train_rf_smote, y_train_rf_smote)

y_pred_rf_smote = rf_smote.predict(X_test_num_scaled)
y_proba_rf_smote = rf_smote.predict_proba(X_test_num_scaled)[:, 1]

In [125]:
roc_auc = roc_auc_score(y_test, y_proba_rf_smote)

metrics_rf_smote = pd.DataFrame({
    "Metric": ["ROC-AUC"],
    "Value": [roc_auc]
})

print("=== Random Forest + SMOTE — Performance summary ===")
display(metrics_rf_smote)

print("=== Confusion matrix ===")
display(pd.DataFrame(
    confusion_matrix(y_test, y_pred_rf_smote),
    index=["True 0", "True 1"],
    columns=["Pred 0", "Pred 1"]
))

print("=== Classification report ===")
print(classification_report(y_test, y_pred_rf_smote, digits=4))

=== Random Forest + SMOTE — Performance summary ===


Metric     Value
0  ROC-AUC  0.579823

=== Confusion matrix ===


Pred 0  Pred 1
True 0    3892    1135
True 1     492     246

=== Classification report ===
              precision    recall  f1-score   support

           0     0.8878    0.7742    0.8271      5027
           1     0.1781    0.3333    0.2322       738

    accuracy                         0.7178      5765
   macro avg     0.5330    0.5538    0.5297      5765
weighted avg     0.7969    0.7178    0.7510      5765



L’application de SMOTE à la base d'apprentissage améliore la capacité de la Random Forest à détecter la classe minoritaire, comme en témoigne l’augmentation du nombre de résiliations correctement identifiées (TP). Toutefois, le gain reste plus limité que pour la régression logistique, et s’accompagne d’une augmentation du nombre de faux positifs.

Ces résultats suggèrent que, dans ce jeu de données, la Random Forest bénéficie moins du rééquilibrage par SMOTE que la régression logistique.


Une alternative au sur-échantillonnage consiste à utiliser la pondération des classes via le paramètre `class_weight="balanced"`.

Cette méthode pénalise davantage les erreurs commises sur la classe minoritaire, sans générer de données synthétiques.

Elle est souvent plus stable et plus simple à déployer en production.

In [128]:
rf_weighted = RandomForestClassifier(
    n_estimators=300,
    max_depth=5,
    min_samples_leaf=2,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_weighted.fit(X_train_num_scaled, y_train)

y_pred_rf_weighted = rf_weighted.predict(X_test_num_scaled)
y_proba_rf_weighted = rf_weighted.predict_proba(X_test_num_scaled)[:, 1]


In [129]:
roc_auc = roc_auc_score(y_test, y_proba_rf_weighted)

metrics_rf_weighted = pd.DataFrame({
    "Metric": ["ROC-AUC"],
    "Value": [roc_auc]
})

print("=== Performance summary ===")
display(metrics_rf_weighted)

print("=== Confusion matrix ===")
display(pd.DataFrame(
    confusion_matrix(y_test, y_pred_rf_weighted),
    index=["True 0", "True 1"],
    columns=["Pred 0", "Pred 1"]
))

print("=== Classification report ===")
print(classification_report(y_test, y_pred_rf_weighted, digits=4))

=== Performance summary ===


Metric     Value
0  ROC-AUC  0.588131

=== Confusion matrix ===


Pred 0  Pred 1
True 0    3337    1690
True 1     400     338

=== Classification report ===
              precision    recall  f1-score   support

           0     0.8930    0.6638    0.7615      5027
           1     0.1667    0.4580    0.2444       738

    accuracy                         0.6375      5765
   macro avg     0.5298    0.5609    0.5030      5765
weighted avg     0.8000    0.6375    0.6953      5765



Le modèle Random Forest entraîné avec class_weight="balanced" obtient un ROC-AUC de 0.588 ce qui indique une capacité de discrimination moyenne mais supérieure au hasard.

La matrice de confusion montre que le modèle détecte 45.8 % des résiliations (rappel de la classe 1), ce qui traduit une bonne sensibilité à la classe minoritaire. En revanche, cette amélioration du rappel s’accompagne d’un nombre élevé de faux positifs, ce qui se reflète dans une précision faible (16.7 %).

Le F1-score de 0.244 montre un compromis entre détection et fiabilité.

Le modèle Random Forest entraîné sur un jeu d’apprentissage rééquilibré par SMOTE obtient un ROC-AUC de 0.580 ce qui est légèrement inférieur à celui du modèle pondéré.

Le rappel de la classe 1 diminue à 33.3 %, indiquant une capacité plus faible à détecter les résiliations. En contrepartie, le nombre de faux positifs est réduit, ce qui se traduit par une précision légèrement supérieure (17.8 %). Toutefois, cette amélioration reste marginale et ne compense pas la perte de rappel.

Le F1-score de 0.232 confirme que le rééquilibrage par SMOTE n’apporte pas de gain global en termes de performance sur la classe minoritaire.

Dans un contexte de prédiction de résiliation, où l’objectif principal est d’identifier un maximum de clients à risque afin de mettre en place des actions préventives, la pondération des classes apparaît plus pertinente. Elle permet de détecter un plus grand nombre de résiliations potentielles.

En revanche, si l’on souhaite limiter le nombre de faux positifs et obtenir un modèle plus prudent, une approche comme SMOTE peut être envisagée.

L’ensemble des résultats et des analyses présentés dans ce notebook sera synthétisé et approfondie dans le rapport final.